name: Java Maven Test Workflow

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test-java-project:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository files
        uses: actions/checkout@v4

      - name: Set up Java for the project
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 26
          cache: maven

      - name: Run Maven unit test
        run: mvn -B test
